from typing import Protocol


class ObjectStorage(Protocol):
	def put_bytes(self, key: str, data: bytes, content_type: str) -> None: ...

	def get_bytes(self, key: str) -> bytes: ...

	def delete(self, key: str) -> None: ...

	def exists(self, key: str) -> bool: ...
